xml4r/libxml-ruby

- ext/libxml/extconf.rb
- SmartOS uses pkgsrc and installs packages under /opt/local. This
change adds the paths to find the libxml library and header files so
gem install "just works"
- Also tweaked formatting of section so it's more readable (to me at
least)
> Build on smartos

- ext/libxml/ruby_xml.c
- ext/libxml/ruby_xml.h
- ext/libxml/ruby_xml_attr.c
- ext/libxml/ruby_xml_document.c
- ext/libxml/ruby_xml_dtd.c
- ext/libxml/ruby_xml_node.c
- ext/libxml/ruby_xml_reader.c
- ext/libxml/ruby_xml_xpath_context.c
- ext/libxml/ruby_xml_xpath_object.c
Maintain a hashtable of mappings from libxml objects to Ruby objects by
address. This replaces the mechanism of using the _private pointer in
the libxml objects.
This supersedes #118, with changes as discussed.
> Store libxml -> Ruby object mappings in a hashtable

- test/tc_parser.rb
In modern shells ulimit is a builtin so calling it within backticks can use odd
file not found errors (below). Process.getrlimit should be a safe replacement.
```
1) Error:
test_fd_gc(TestParser):
Errno::ENOENT: No such file or directory - ulimit -n
~/projects/oss/libxml-ruby/test/tc_parser.rb:249:in ``'
~/projects/oss/libxml-ruby/test/tc_parser.rb:249:in `test_fd_gc'
```
> Use Process.getrlimit instead of `ulimit` in the tests.

- README.rdoc
There is a typo in README.rdoc.
> Fix typo in README

- lib/libxml/node.rb
I find typo (maybe it is) on inner_xml() RDoc.
If it is actually, please merge it.
> Fix typo on the part of documenting inner_xml()

- test/tc_namespace.rb
- test/tc_namespaces.rb
- test/tc_parser_context.rb
- test/tc_reader.rb
- test/tc_schema.rb
Remove all the depreciation warnings:
e.g.
```ruby
DEPRECATED: Use assert_nil if expecting nil from [...]. This will fail in Minitest 6.
```
> Remove assert_equal(nil, ...) in favor of assert_nil(...)

- libxml-ruby.gemspec
```
$ gem build libxml-ruby.gemspec
Invalid gemspec in [libxml-ruby.gemspec]: uninitialized constant Gem::Specification::DateTime
Did you mean?  Gem::Specification::DateLike
ERROR:  Error loading gemspec. Aborting.
```
> Avoid gem build failure:

- setup.rb
Otherwise I get:
```ruby
setup.rb:283: warning: key "bin-dir" is duplicated and overwritten on line 284
```
> Remove duplicate hash key in setup.rb

- ext/libxml/ruby_xml_reader.c
- test/tc_namespaces.rb
> Replaced deprecated `assert_euqal(nil, expected)`

- ext/libxml/ruby_xml.c
- test/test_node.rb
- test/test_xml.rb
Allows empty XML nodes to be serialized as `<test></test>` instead of
the default `<test/>`.
Change the default with `XML.default_save_no_empty_tags = true`
> Add support for libxml2 option xmlSaveNoEmptyTags

- README.rdoc
Although perhaps beyond the scope of install instructions, I needed to remind myself how to do this today and also noticed it has come up several times in issues.  While adding the help, I also tidied up elsewhere.
Left as separate commits in case some parts are desired but others not.
> Add build flag help to installation instructions.

- libxml-ruby.gemspec
Old address no longer works (gitlab pages is now .gitlab.io). Closes #170 (Project description will need manual update through)
> Update homepage in gemspec

- test/test_sax_parser.rb
s/refuse_nil/refute_nil/
Thanks to @mapreri for catching this (on PR 173).
> Fix typo on test/test_sax_parser.rb

- ext/libxml/ruby_xml_node.c
This patch fixes a memory leak in `node.path` method.
Demo:
```ruby
def test_path_memory
node = LibXML::XML::Node.new('node')
p `ps -o rss= -p #{Process.pid}`.to_f
1000000.times do
node.path
end
p `ps -o rss= -p #{Process.pid}`.to_f
end
```
> Fix memory leak in `rxml_node_path` funcion (node.path method)

- .github/workflows/mri.yml
ruby/setup-ruby is the repo with the custom action that loads Ruby and sets up the environment for it.
When PR #177 was done, several updates to ruby/setup-ruby were not yet merged. MSP-Greg/ruby-setup-ruby contained many of those updates, so CI was switched to that.
ruby/setup-ruby is now working with Windows-2022 image, so switch back to it.
> GitHub Actions - update to use ruby/setup-ruby

- ext/libxml/ruby_xml.c
Only call xmlGetFeaturesList if LIBXML_LEGACY_ENABLED is defined. Most
distros still ship libxml2 with legacy features enabled, but this will
change.
> xmlGetFeaturesList is a legacy function

- ext/libxml/ruby_xml_namespace.c
- ext/libxml/ruby_xml_schema.c
- ext/libxml/ruby_xml_version.h
- test/model/shiporder.rnc
- test/model/shiporder.rng
- test/model/shiporder.xsd
- test/model/shiporder_bad.xsd
- test/model/shiporder_import.xsd
- test/test_schema.rb
Many schemas that use imported schemas for other targeted namespaces allow those other namespace elements to appear within the original targeted namespace.   However, it is not currently possible to find an imported schema type for one of those imported elements without having a list of the imported element names.
Also, it is impossible to distinguish during test whether a value being returned is an elemDecl or a typeDecl when the test names are the same.  Hence the change of the type name for 'shiporder' to be 'shiporderType'.   This allows the test to distinguish whether the element or the type name was returned.
> Add schema.imported_elements so we can find those imported elements

- ext/libxml/ruby_xml_schema.c
- ext/libxml/ruby_xml_schema.h
- ext/libxml/ruby_xml_schema_attribute.c
- ext/libxml/ruby_xml_schema_element.c
- ext/libxml/ruby_xml_schema_facet.c
- ext/libxml/ruby_xml_schema_type.c
The primary reason for this change is to make debugging easier.   The default Ruby to_str method will list an object with it's instance variables.   In example, the following is what a Schema::Element object looks like without using instance variables:
```
(byebug) schema_elem
#<LibXML::XML::Schema::Element:0x0000562ceedd4c00>
```
whereas with instance variables it would look like:
```
(byebug) schema_elem
#<LibXML::XML::Schema::Element:0x000056226531b2c0 @name="manifest", @value=nil, @namespace="http://www.imsproject.org/xsd/imscp_rootv1p1p2", @type=#<LibXML::XML::Schema::Type:0x000056226531ad48 @name="manifestType", @kind=5, @namespace="http://www.imsproject.org/xsd/imscp_rootv1p1p2">>
```
Note: I did not convert all the methods to use instance variables because some of those methods …
> Convert some schema method accessors to use instance variables with attr_reader methods.

- lib/libxml-ruby.rb
This reverts commit 332fd1db337db905bf4b17191f3d7ca76f629cd0.
Because this causes "assigned but unused variable" warning when libxml-ruby 3.2.4 is being required with `-W`.
```
$ ruby -we "require'libxml-ruby'"
.../libxml-ruby-3.2.4/lib/libxml-ruby.rb:7: warning: assigned but unused variable - e
```
> Revert "Store exception to local object for easier debugging." that warns

- ext/libxml/extconf.rb
This solution is for optionally building the Ruby gem package here with the LibXML configure script parameter ( `--with-xml2-config` ). It helped me resolve my encounter with the https://github.com/xml4r/libxml-ruby/issues/193 issue, and it should hopefully do so for others as well!
> Introduce new alternative Homebrew installation search paths to extconf makefile

- ext/libxml/ruby_xml_relaxng.c
See https://github.com/xml4r/libxml-ruby/issues/198
> ruby_xml_relaxng.c: rb_undef_alloc_func(cXMLRelaxNG);

- lib/libxml/schema/element.rb
- test/test_schema.rb
In [this commit](https://github.com/xml4r/libxml-ruby/commit/133096bc7adfb1b9ca5be2e49e623c8880fec9ee#diff-ff32e4dff2433e31f170b6f43842c940bec1c3581a07a5e3bc44887ce973fcc0L67-L76) the `min_occurs` and `max_occurs` getters were removed, saying they were "invalid". The additional message in [HISTORY](https://github.com/xml4r/libxml-ruby/blob/master/HISTORY#L63C111-L63C111) states:
> Remove SchemaElement#minOccurs and SchemaElement#maxOccurs since they actually did not work (Charlie Savage)
[Additional history here](https://github.com/search?q=repo%3Axml4r%2Flibxml-ruby+min_occurs&type=commits)
I'm not aware of any more context surrounding the change, but those methods were still referenced by the Schema::Element's `array?` and `required?` methods. This PR adds tests for those two methods …
> Fix Schema::Element required? and array? methods

- ext/libxml/ruby_xml_attr_decl.c
- ext/libxml/ruby_xml_attributes.c
- ext/libxml/ruby_xml_schema_attribute.c
- ext/libxml/ruby_xml_schema_element.c
- ext/libxml/ruby_xml_schema_type.c
- ext/libxml/ruby_xml_xpath_object.c
This is continuous of #202. It seems that `libxml-ruby` still has warnings about "undefining the allocator of T_DATA class " and this PR fixes all that remains.
> Fix Ruby warnings about t data classes

- ext/libxml/extconf.rb
Hello,
This adds detection for optional zlib support that may be available indirectly through libxml2, to `extconf.rb`.
Background:
While this gem doesn't directly depend on zlib, it can leverage zlib functionality when available through libxml2.  Currently, the `HAVE_ZLIB_H` macro is never defined, which means zlib support is always disabled even when zlib is actually available via libxml2.  This change allows the extension to conditionally use zlib features.
Thank you.
> Add optional zlib support detection in extconf
